config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :code_schools
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code_school.rb
class CodeSchool < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :code_school
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/code_schools_controller.rb
class CodeSchoolsController < ApplicationController
  before_action :set_code_school, only: [:show, :edit, :update, :destroy]

  # GET /code_schools
  # GET /code_schools.json
  def index
    @code_schools = CodeSchool.all
  end

  # GET /code_schools/1
  # GET /code_schools/1.json
  def show
  end

  # GET /code_schools/new
  def new
    @code_school = CodeSchool.new
  end

  # GET /code_schools/1/edit
  def edit
  end

  # POST /code_schools
  # POST /code_schools.json
  def create
    @code_school = CodeSchool.new(code_school_params)

    respond_to do |format|
      if @code_school.save
        format.html { redirect_to @code_school, notice: 'Code school was successfully created.' }
        format.json { render :show, status: :created, location: @code_school }
      else
        format.html { render :new }
        format.json { render json: @code_school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /code_schools/1
  # PATCH/PUT /code_schools/1.json
  def update
    respond_to do |format|
      if @code_school.update(code_school_params)
        format.html { redirect_to @code_school, notice: 'Code school was successfully updated.' }
        format.json { render :show, status: :ok, location: @code_school }
      else
        format.html { render :edit }
        format.json { render json: @code_school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /code_schools/1
  # DELETE /code_schools/1.json
  def destroy
    @code_school.destroy
    respond_to do |format|
      format.html { redirect_to code_schools_url, notice: 'Code school was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code_school
      @code_school = CodeSchool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_school_params
      params.require(:code_school).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :code_school_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_schools_helper.rb
module CodeSchoolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/code_schools/_form.html.erb
<%= form_with(model: code_school, local: true) do |form| %>
  <% if code_school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(code_school.errors.count, "error") %> prohibited this code_school from being saved:</h2>

      <ul>
      <% code_school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :code_school_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/code_schools/edit.html.erb
<h1>Editing Code School</h1>

<%= render 'form', code_school: @code_school %>

<%= link_to 'Show', @code_school %> |
<%= link_to 'Back', code_schools_path %>

app/views/code_schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Code Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @code_schools.each do |code_school| %>
      <tr>
        <td><%= code_school.name %></td>
        <td><%= link_to 'Show', code_school %></td>
        <td><%= link_to 'Edit', edit_code_school_path(code_school) %></td>
        <td><%= link_to 'Destroy', code_school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Code School', new_code_school_path %>

app/views/code_schools/new.html.erb
<h1>New Code School</h1>

<%= render 'form', code_school: @code_school %>

<%= link_to 'Back', code_schools_path %>

app/views/code_schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @code_school.name %>
</p>

<%= link_to 'Edit', edit_code_school_path(@code_school) %> |
<%= link_to 'Back', code_schools_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :code_school_id %>
    <%= form.text_field :code_school_id, id: :user_code_school_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Code school</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.code_school %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Code school:</strong>
  <%= @user.code_school %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>